services:
  - type: web
    name: loanshark-backend
    env: node
    plan: free
    region: oregon
    buildCommand: yarn install && yarn prisma:generate && yarn prisma:migrate && yarn server:build
    startCommand: yarn start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
    disk:
      name: data
      mountPath: /data
      sizeGB: 1