services:
  - type: web
    name: loanshark-backend
    env: node
    plan: free
    region: oregon
    buildCommand: npm install && npm run prisma:generate && npm run prisma:push && npm run server:build
    startCommand: yarn start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: API_KEY
        sync: false
      - key: DATABASE_URL
        value: file:/data/dev.db
    disk:
      name: data
      mountPath: /data
      sizeGB: 1